set(THIRD_PARTY_CMAKE_DIR "${CMAKE_SCRIPTS_DIR}/third-party-cmake")
include("${THIRD_PARTY_CMAKE_DIR}/abseil-cpp.cmake")
include("${THIRD_PARTY_CMAKE_DIR}/libsrtp.cmake")
include("${THIRD_PARTY_CMAKE_DIR}/libvpx.cmake")
include("${THIRD_PARTY_CMAKE_DIR}/pffft.cmake")
include("${THIRD_PARTY_CMAKE_DIR}/usrsctp2.cmake")
include("${THIRD_PARTY_CMAKE_DIR}/libyuv.cmake")
include("${THIRD_PARTY_CMAKE_DIR}/openssl2.cmake")